name: Review an LLM claim
description: Submit a review status for an Erdos or MathOverflow problem.
title: "Review: "
labels:
  - review
body:
  - type: dropdown
    id: problem_type
    attributes:
      label: Problem type
      options:
        - Erdos
        - MO
    validations:
      required: true
  - type: input
    id: problem_id
    attributes:
      label: Problem ID
      description: Erdos problem number or MO question ID (digits only).
      placeholder: "665"
    validations:
      required: true
  - type: dropdown
    id: verdict
    attributes:
      label: Verdict
      options:
        - Unreviewed / flagging only
        - Reviewed - incorrect
        - Reviewed - technicality / loophole
        - Reviewed - trivial / already known
        - Reviewed - partial progress
        - Reviewed - plausible but incomplete
        - Verified / accepted (with citation)
    validations:
      required: true
  - type: textarea
    id: explanation
    attributes:
      label: Explanation
      description: Short summary of your reasoning or checks.
      placeholder: What did you check? Why this verdict?
    validations:
      required: true
  - type: textarea
    id: citations
    attributes:
      label: Citation links (required for Verified / accepted)
      description: Include at least one URL if you select Verified / accepted. One per line.
      placeholder: https://...
    validations:
      required: false
  - type: input
    id: discussion_link
    attributes:
      label: Related discussion link (optional)
      description: Link to the GitHub discussion, MO comment, or other relevant thread.
      placeholder: https://github.com/.../discussions/...
    validations:
      required: false
